Specify *pkgbuild::*has_devel()
Running code as in book (i.e., without this specification) caused error messages on my system:
====
> library(devtools)
> has_devel()
Error: could not find function "has_devel"
> devtools::has_devel()
Error: 'has_devel' is not an exported object from 'namespace:devtools'
> ??has_devel
> pkgbuild::has_devel()
[1] TRUE
====